In [1]:
import pandas as pd

s = pd.read_csv('sample_submission.csv')
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

FileNotFoundError: [Errno 2] File sample_submission.csv does not exist: 'sample_submission.csv'

In [24]:
from shutil import copyfile
import os

path = 'images/'
train_path = 'train_image/'
test_path = 'test_image/'

os.mkdir(train_path) if not os.path.exists(train_path) else None
os.mkdir(test_path) if not os.path.exists(test_path) else None

for image in os.listdir(path):
    kind, name = image.split('_')
    if kind == 'Test':
        copyfile(path+image, test_path+name)
    else:
        copyfile(path+image, train_path+name)
    


In [15]:

for i in train['image_id']:
    print(i)

Train_0
Train_1
Train_2
Train_3
Train_4
Train_5
Train_6
Train_7
Train_8
Train_9
Train_10
Train_11
Train_12
Train_13
Train_14
Train_15
Train_16
Train_17
Train_18
Train_19
Train_20
Train_21
Train_22
Train_23
Train_24
Train_25
Train_26
Train_27
Train_28
Train_29
Train_30
Train_31
Train_32
Train_33
Train_34
Train_35
Train_36
Train_37
Train_38
Train_39
Train_40
Train_41
Train_42
Train_43
Train_44
Train_45
Train_46
Train_47
Train_48
Train_49
Train_50
Train_51
Train_52
Train_53
Train_54
Train_55
Train_56
Train_57
Train_58
Train_59
Train_60
Train_61
Train_62
Train_63
Train_64
Train_65
Train_66
Train_67
Train_68
Train_69
Train_70
Train_71
Train_72
Train_73
Train_74
Train_75
Train_76
Train_77
Train_78
Train_79
Train_80
Train_81
Train_82
Train_83
Train_84
Train_85
Train_86
Train_87
Train_88
Train_89
Train_90
Train_91
Train_92
Train_93
Train_94
Train_95
Train_96
Train_97
Train_98
Train_99
Train_100
Train_101
Train_102
Train_103
Train_104
Train_105
Train_106
Train_107
Train_108
Train_109
Train_110


In [3]:
import keras
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train/255.
x_test = x_test/255. 
num_classes = 10 
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print(y_train)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [31]:
import os
import cv2
import numpy as np
import pandas as pd

from PIL import Image

def letterbox_image(image, size):
    '''resize image with unchanged aspect ratio using padding'''
    iw, ih = image.size
    w, h = size
    scale = min(w/iw, h/ih)
    nw = int(iw*scale)
    nh = int(ih*scale)

    image = image.resize((nw,nh), Image.BICUBIC)
    new_image = Image.new('RGB', size, (128,128,128))
    new_image.paste(image, ((w-nw)//2, (h-nh)//2))
    return new_image

def _preprocess_data(image_path, csv_path):
    csv = pd.read_csv(csv_path)
    labels = True if csv.shape[1] == 5 else False
    for image in train['image_id']:
        path = image_path + image + '.jpg'
        im = Image.open(path)
        im = np.array(letterbox_image(im, (600,600)))
        im = np.reshape(im,[1]+list(im.shape))
        if 'X' not in locals():
            X = im
        else:
            X = np.concatenate((X,im))

    X = X/255
    if labels:
        y = csv.loc[:, 'healthy':].values
        return X,y
    else:
        return X
    
image_path = 'C:/Users/emage/OneDrive/Desktop/apple_k/data/images/'
csv_path = 'C:/Users/emage/OneDrive/Desktop/apple_k/data/train.csv'
x,y = _preprocess_data(image_path, csv_path)
print(x.shape)

KeyboardInterrupt: 

In [29]:
a = np.random.randint(0,10,(10,10,3))
b = np.random.randint(0,10,(10,10,3))
a = np.reshape(a,[1]+list(a.shape))
b = np.reshape(b,[1]+list(b.shape))
c = np.concatenate((a,b))
# print(c.shape)
if 'c' not in locals():
    print('ok')

In [ ]:
from keras.preprocessing.image import ImageDataGenerator

